framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true

  # Note that the session will be started ONLY if you read or write from it.
  session: true

  #esi: true
  #fragments: true
  cors:
    allow_origin: ['*'] 
    allow_headers: ['*']
    allow_methods: ['POST', 'GET', 'PUT', 'DELETE']
    max_age: 3600
    
  nelmio_cors:
    paths:
      '^/api/':
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600
